#!/bin/bash
# init-firewall.sh — setup iptables allowlist
# Yêu cầu: container chạy với --cap-add=NET_ADMIN --cap-add=NET_RAW
set -euo pipefail

ALLOWLIST_FILE="${1:-/etc/allowlist.txt}"
BROKER_IP="${2:-}"
BROKER_PORT="${3:-}"
INBOUND_PORTS="${4:-}"

if [[ ! -f "$ALLOWLIST_FILE" ]]; then
  echo "⚠️  Không có allowlist file — skip firewall"
  exit 0
fi

echo "🔥 Setup firewall với allowlist: $ALLOWLIST_FILE"

# Flush rules cũ
iptables -F
iptables -X
# Do not flush the nat table. On Docker user-defined networks, Docker's
# embedded DNS at 127.0.0.11 depends on nat rules inside the container
# namespace; removing them makes every allowlist lookup resolve to nothing.

# Default DROP
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

# Cho phép loopback
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Cho phép DNS (cần để resolve domain trong allowlist)
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT
iptables -A INPUT -p tcp --sport 53 -j ACCEPT

# Cho phép established connections
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Optional explicit inbound ports. Used by the broker sidecar so the paired
# clau container can call http://broker:8080 while the broker still keeps a
# default-deny firewall for everything else.
for port in ${INBOUND_PORTS//,/ }; do
  [[ -z "$port" ]] && continue
  if [[ "$port" =~ ^[0-9]+$ ]] && (( 10#$port >= 1 && 10#$port <= 65535 )); then
    iptables -A INPUT -p tcp --dport "$port" -j ACCEPT
    echo "📥 Inbound rule: tcp/$port"
  else
    echo "⚠️  Skip invalid inbound port: $port"
  fi
done

# Tạo ipset cho các IP allowlist
ipset destroy allowed-domains 2>/dev/null || true
ipset create allowed-domains hash:ip

# Resolve mỗi domain → add vào ipset
# `|| [[ -n "$domain" ]]`: handle allowlist files without trailing newline
# (otherwise `read` returns 1 on the last line and the loop body is skipped,
# leaving the ipset empty → all HTTPS dropped → claude hangs at startup).
while IFS= read -r domain || [[ -n "$domain" ]]; do
  # Bỏ comment và dòng trống
  domain="${domain%%#*}"
  domain="$(echo "$domain" | xargs)"
  [[ -z "$domain" ]] && continue

  echo "  → Resolving $domain"
  # getent vì dig không có sẵn trong debian slim
  ips=$(getent ahosts "$domain" | awk '{print $1}' | sort -u || true)
  for ip in $ips; do
    ipset add allowed-domains "$ip" 2>/dev/null || true
  done
done < "$ALLOWLIST_FILE"

# Chỉ cho phép outbound HTTPS/HTTP tới IP trong ipset
iptables -A OUTPUT -p tcp --dport 443 -m set --match-set allowed-domains dst -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80  -m set --match-set allowed-domains dst -j ACCEPT

# Sidecar broker. Claude container reaches its paired broker on the dedicated
# docker network. Launcher resolves the broker IP and passes BROKER_IP / BROKER_PORT.
if [[ -n "${BROKER_IP:-}" && -n "${BROKER_PORT:-}" ]]; then
  iptables -A OUTPUT -p tcp -d "$BROKER_IP" --dport "$BROKER_PORT" -j ACCEPT
  echo "🔗 Broker rule: $BROKER_IP:$BROKER_PORT"
fi

echo "✅ Firewall active. Allowed IPs: $(ipset list allowed-domains | grep -c '^[0-9]')"

# DNS-coupled allowlist refresh.
#
# Without this, the ipset above is a startup snapshot. Meta and Google
# rotate their anycast/CDN IPs continuously; a few hours after startup
# `graph.facebook.com` resolves to an IP that isn't in the ipset → outbound
# 443 hits the default-DROP OUTPUT policy → connect timeout. Symptom looks
# like the broker is hanging on POSTs but is actually firewalled.
#
# Fix: route DNS through a local dnsmasq that has `ipset=/<domain>/allowed-domains`
# directives. Every time an allowlisted domain is resolved, dnsmasq adds the
# answer IPs to the ipset before returning them to the caller — so the
# resolution itself unblocks the connection that's about to use it.
if command -v dnsmasq >/dev/null 2>&1; then
  conf=/etc/dnsmasq.d/clau-allowlist.conf
  mkdir -p /etc/dnsmasq.d
  {
    echo "# Auto-generated by init-firewall.sh — do not edit by hand."
    echo "no-resolv"
    echo "server=127.0.0.11"      # Docker's embedded DNS (container names + recursion)
    echo "listen-address=127.0.0.1"
    echo "bind-interfaces"
    echo "no-hosts"
    echo "log-queries=no"
    echo "pid-file=/run/dnsmasq-clau.pid"
    while IFS= read -r domain || [[ -n "$domain" ]]; do
      domain="${domain%%#*}"
      domain="$(echo "$domain" | xargs)"
      [[ -z "$domain" ]] && continue
      echo "ipset=/$domain/allowed-domains"
    done < "$ALLOWLIST_FILE"
  } > "$conf"

  # Replace any prior instance from a previous entrypoint run.
  if [[ -f /run/dnsmasq-clau.pid ]] && kill -0 "$(cat /run/dnsmasq-clau.pid 2>/dev/null)" 2>/dev/null; then
    kill "$(cat /run/dnsmasq-clau.pid)" 2>/dev/null || true
  fi

  if dnsmasq --conf-file="$conf"; then
    # Repoint resolver to dnsmasq. This stays inside the container — Docker
    # rewrites /etc/resolv.conf on container start, but it's a regular
    # bind-mounted file we can overwrite at runtime.
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
    echo "🌐 dnsmasq running on 127.0.0.1 — ipset auto-refreshes on every DNS lookup"
  else
    echo "⚠️  dnsmasq failed to start; ipset will go stale on Meta/Google IP rotation"
  fi
else
  echo "ℹ️  dnsmasq not installed — ipset is a startup snapshot; expect timeouts after CDN IP rotation"
fi
